// <auto-generated />
namespace CurrencyExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_in_DateTime_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_in_DateTime_property));
        
        string IMigrationMetadata.Id
        {
            get { return "202205221357225_Change_in_DateTime_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
